support targets in release workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -9,6 +9,7 @@ env:
   CARGO_TERM_COLOR: always
   # Fail CI on all warnings
   RUSTFLAGS: "-Dwarnings"
+  TARGETS_TO_BUILD: x86_64-unknown-linux-gnu
 
 jobs:
 
@@ -22,11 +23,23 @@ jobs:
         uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
       - uses: ./.github/setup-env/
       - run: just lint
-      - run: just test
       - run: |
-          version="$(./target/release/badger --version | cut -d" " -f2)"
+          for target in ${TARGETS_TO_BUILD}; do
+            echo "build / test for ${target}..."
+            just test "${target}"
+          done
+      - run: |
+          version="$(./target/x86_64-unknown-linux-gnu/release/badger --version | cut -d" " -f2)"
+          if [ "${version}" == "" ]; then
+            echo "error determining version"
+            exit 1
+          fi
+          mkdir artifacts
+          for target in ${TARGETS_TO_BUILD}; do
+            mv "target/${target}/release/badger" "artifacts/badger-${target}"
+          done
           gh release create "v${version}" \
             --draft \
             --generate-notes \
             --fail-on-no-commits \
-            target/release/badger
+            artifacts/*
